apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-sb
  labels:
    app: demo-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      run: demo
      app: demo
  template:
    metadata:
      labels:
        run: demo
        app: demo
    spec:
      containers:
        - name: demo
          image: sb:1.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
